"""test

Revision ID: 7d92a306e529
Revises: f0cd5ee44a3a
Create Date: 2025-08-14 23:38:11.595274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d92a306e529'
down_revision: Union[str, Sequence[str], None] = 'f0cd5ee44a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'p')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('p', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
