"""test

Revision ID: f0cd5ee44a3a
Revises: 05a01ffc3c36
Create Date: 2025-08-14 23:37:21.099283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cd5ee44a3a'
down_revision: Union[str, Sequence[str], None] = '05a01ffc3c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('p', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'p')
    # ### end Alembic commands ###
